
#ifndef REGENCY_DEFINES_H
#define REGENCY_DEFINES_H

namespace regency {

#define WORLD_SIZE 250
#define DUP_FACTOR 1

#define OCEAN_SIZE 25000
#define LAKE_SIZE 2500
#define CONTINENT_SIZE 10000
#define DEFAULT_WATER_LEVEL 0.3

#define RENDER_SIZE 100
#define WINDOW_SIZE 1000
#define VIEW_DISTANCE 100

#define MS_PER_TICK 20
}

#endif // REGENCY_DEFINES_H
